name: seongnam
description: Simple tap effect package for Flutter.
version: 0.0.2
homepage: https://github.com/Apeiro-Corp/seongnam
repository: https://github.com/Apeiro-Corp/seongnam
documentation: https://github.com/Apeiro-Corp/seongnam

topics:
  - tap-effect
  - vibrate
  - vibrate-tap

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
